spring:
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://mysqldata:3306/vli #jdbc:mysql://localhost:3306/vns?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: max
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
flyway:
  locations: classpath:/db/migration
app:
  jwtSecret: SecretKey
  jwtExpirationMs: 86400000